projects:
  prisma:
    schemaPath: src/schema.graphql
    extensions:
      prisma: prisma/prisma.yml


#projects:
#  app:
#    schemaPath: src/schema.graphql
#    extensions:
#      prisma: prisma/prisma.yml
#      codegen:
#        - generator: prisma-binding
#          language: graphql
#          output:
#            binding: src/generated/prisma.graphql
#      endpoints:
#        default: http://localhost:4000
#  prisma:
#    schemaPath: src/generated/prisma.graphql
#    extensions:
#      prisma: prisma/prisma.yml
